# Generated by Django 5.2.5 on 2025-08-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Concurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("instituicao", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
