# Generated by Django 5.2.5 on 2025-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concurso", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concurso",
            old_name="nome",
            new_name="cargo",
        ),
        migrations.AddField(
            model_name="concurso",
            name="orgao",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
