# Generated by Django 5.2.5 on 2025-08-13 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assunto", "0001_initial"),
        ("concurso", "0001_initial"),
        ("materia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("alternativa_a", models.TextField()),
                ("alternativa_b", models.TextField()),
                ("alternativa_c", models.TextField()),
                ("alternativa_d", models.TextField()),
                ("alternativa_e", models.TextField()),
                (
                    "resposta_correta",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                        ],
                        max_length=1,
                    ),
                ),
                ("comentario_resposta", models.TextField(blank=True, null=True)),
                (
                    "assunto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assunto.assunto",
                    ),
                ),
                (
                    "concurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="concurso.concurso",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="materia.materia",
                    ),
                ),
            ],
        ),
    ]
