# Generated by Django 5.2.5 on 2025-08-13 23:42

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="alternativa_a",
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_b",
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_c",
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_d",
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_e",
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name="questao",
            name="enunciado",
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
