# Generated by Django 5.2.5 on 2025-08-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="alternativa_a",
            field=models.TextField(verbose_name="Alternativa A"),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_b",
            field=models.TextField(verbose_name="Alternativa B"),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_c",
            field=models.TextField(verbose_name="Alternativa C"),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_d",
            field=models.TextField(verbose_name="Alternativa D"),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_e",
            field=models.TextField(verbose_name="Alternativa E"),
        ),
        migrations.AlterField(
            model_name="questao",
            name="enunciado",
            field=models.TextField(verbose_name="Enunciado"),
        ),
    ]
