# Generated by Django 5.2.5 on 2025-08-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questao", "0002_alter_questao_alternativa_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questao",
            name="alternativa_c",
            field=models.TextField(blank=True, verbose_name="Alternativa C"),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_d",
            field=models.TextField(blank=True, verbose_name="Alternativa D"),
        ),
        migrations.AlterField(
            model_name="questao",
            name="alternativa_e",
            field=models.TextField(blank=True, verbose_name="Alternativa E"),
        ),
    ]
