# Generated by Django 5.2.5 on 2025-08-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulado", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulado",
            name="duracao_simulado",
            field=models.IntegerField(default=120),
        ),
    ]
