# Generated by Django 5.2.5 on 2025-08-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulado", "0002_simulado_duracao_simulado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulado",
            name="duracao_simulado",
        ),
        migrations.AddField(
            model_name="simulado",
            name="data_fim",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="simulado",
            name="data_inicio",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
