# Generated by Django 5.2.5 on 2025-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulado",
            "0003_remove_simulado_duracao_simulado_simulado_data_fim_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="simulado",
            name="duracao_simulado",
            field=models.IntegerField(default=120),
        ),
    ]
