# Generated by Django 5.2.5 on 2025-08-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materia",
            name="nome",
            field=models.CharField(max_length=255),
        ),
    ]
