# Generated by Django 5.2.5 on 2025-08-13 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questao", "0001_initial"),
        ("simulado", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RespostaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alternativa_escolhida", models.CharField(max_length=1)),
                ("correta", models.BooleanField()),
                ("data_resposta", models.DateTimeField(auto_now_add=True)),
                (
                    "questao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questao.questao",
                    ),
                ),
                (
                    "simulado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="simulado.simulado",
                    ),
                ),
            ],
        ),
    ]
