# Generated by Django 5.2.5 on 2025-08-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("respostausuario", "0001_initial"),
        ("simulado", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="respostausuario",
            name="simulado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="simulado.simulado"
            ),
        ),
    ]
